#!/bin/sh
# Creates an "Install KoruX" icon on the live session tested with:
# Xfce, LXDE, LXqt, Gnome, KDE, Mate, Cinnamon

# We query xdg-user-dir because the Desktop directory has different
# names for different languages
DESKTOP=$(xdg-user-dir DESKTOP)

# Create ~/Desktop just in case this runs before the xdg folder
# creation script.
mkdir -p $DESKTOP

# Among the KoruX desktop environments, LXDE is the only one
# that behaves completely different.
if [ -f /usr/bin/lxsession ]; then
    echo "[Desktop Entry]" > $DESKTOP/install-korux.desktop
    echo "Type=Link" >> $DESKTOP/install-korux.desktop
    echo "Name=Install KoruX" >> $DESKTOP/install-korux.desktop
    echo "Icon=install-korux" >> $DESKTOP/install-korux.desktop
    echo "URL=/usr/share/applications/install-korux.desktop" \
          >> $DESKTOP/install-korux.desktop
else
    cp /usr/share/applications/install-korux.desktop $DESKTOP
    # Xfce needs this executable otherwise it complains, everything
    # else doesn't seem to care either way.
    chmod +x $DESKTOP/install-korux.desktop
fi

if [ "$XDG_CURRENT_DESKTOP" = "XFCE" ]; then
    #Set desktop launcher as trusted under gnome/xfce (See: #1037299)
    gio set --type=string ~/Desktop/install-korux.desktop \
        metadata::trusted true
    gio set --type=string ~/Desktop/install-korux.desktop \
        metadata::xfce-exe-checksum \
        "$(sha256sum ~/Desktop/install-korux.desktop | cut -f1 -d' ')"
    touch ~/Desktop/install-korux.desktop
fi
